[{"user_id": 19191, "stars": [], "topic_id": 11205, "date_created": 1299465653.1220901, "message": "My goal is to let the system-wide package manager of my distrib manage as few python stuff as possible, so just the python 2 interpreter (python2 on my machine, as python has to default to python3 otherwise it breaks a lot of stuff). I roughly did the following to set up the basic tools:\n\n~/.pydistutil.cfg\n[install]\nprefix=/home/agravier/Dropbox/dev/devenv/python2\n\n~/.bash_profile\n[...]\nDROPBOX=\"$HOME\"/Dropbox\nPATH=$PATH:/usr/local/bin:$HOME/root/bin:$HOME/root/usr/bin:$HOME/root/usr/local/bin:$ANDROID_SDK_DIR/tools:$DROPBOX/dev/devenv/python2/bin:$DROPBOX/dev/devenv/bin\nexport PATH\nPYTHONPATH=.:/usr/lib/python2.7/site-packages:$HOME/root/lib/python2.7/site-packages:$HOME/root/usr/lib/python2.7/site-packages:$DROPBOX/dev/devenv/python2/lib/python2.7/site-packages\nPYTHONDOCS=/usr/share/doc/python2/html/\nexport PYTHONPATH PYTHONDOCS\nexport VIRTUALENVWRAPPER_PYTHON=`which python2`\nexport WORKON_HOME=$DROPBOX/dev/devenv/python2/virtualenvs\nsource $DROPBOX/dev/devenv/python2/bin/virtualenvwrapper.sh\n[...]\n\ndistribute_setup.py\n\npip install virtualenv\npip install virtualenvwrapper\n have\n$  which easy_install\n/home/agravier/Dropbox/dev/devenv/python2/bin/easy_install", "group_id": 1535, "id": 283598}, {"user_id": 19191, "stars": [], "topic_id": 11205, "date_created": 1299465712.7068419, "message": "After sourcing bash_profile again (and removing ~/.pydistutil.cfg):\n\nagravier virtualenvs  $  mkvirtualenv temp\nNew python executable in temp/bin/python2\nAlso creating executable in temp/bin/python\nInstalling setuptools...........done.\n  Complete output from command /home/agravier/Dropbox/dev/dev...thon2 /home/agravier/Dropbox/dev/dev...stall /home/agravier/Dropbox/dev/dev...ar.gz:\n  /home/agravier/Dropbox/dev/devenv/python2/virtualenvs/temp/bin/python2: can't open file '/home/agravier/Dropbox/dev/devenv/python2/virtualenvs/temp/bin/easy_install': [Errno 2] No such file or directory\n----------------------------------------\nTraceback (most recent call last):\n  File \"/home/agravier/Dropbox/dev/devenv/python2/bin/virtualenv\", line 9, in <module>\n    load_entry_point('virtualenv==1.5.1', 'console_scripts', 'virtualenv')()\n  File \"/home/agravier/Dropbox/dev/devenv/python2/lib/python2.7/site-packages/virtualenv.py\", line 558, in main\n    prompt=options.prompt)\n  File \"/home/agravier/Dropbox/dev/devenv/python2/lib/python2.7/site-packages/virtualenv.py\", line 656, in create_environment\n    install_pip(py_executable)\n  File \"/home/agravier/Dropbox/dev/devenv/python2/lib/python2.7/site-packages/virtualenv.py\", line 415, in install_pip\n    filter_stdout=_filter_setup)\n  File \"/home/agravier/Dropbox/dev/devenv/python2/lib/python2.7/site-packages/virtualenv.py\", line 624, in call_subprocess\n    % (cmd_desc, proc.returncode))\nOSError: Command /home/agravier/Dropbox/dev/dev...thon2 /home/agravier/Dropbox/dev/dev...stall /home/agravier/Dropbox/dev/dev...ar.gz failed with error code 2\nagravier virtualenvs  $  ls temp\nbin  include  lib\nagravier virtualenvs  $  ls temp/bin\npython  python2\nagravier virtualenvs  $  cp `which easy_install` temp/bin/ && mkvirtualenv temp\nNew python executable in temp/bin/python2\nNot overwriting existing python script temp/bin/python (you must use temp/bin/python2)\nInstalling setuptools............done.\nvirtualenvwrapper.user_scripts creating /home/agravier/Dropbox/dev/devenv/python2/virtualenvs/temp/bin/predeactivate\nvirtualenvwrapper.user_scripts creating /home/agravier/Dropbox/dev/devenv/python2/virtualenvs/temp/bin/postdeactivate\nvirtualenvwrapper.user_scripts creating /home/agravier/Dropbox/dev/devenv/python2/virtualenvs/temp/bin/preactivate\nvirtualenvwrapper.user_scripts creating /home/agravier/Dropbox/dev/devenv/python2/virtualenvs/temp/bin/postactivate\nvirtualenvwrapper.user_scripts creating /home/agravier/Dropbox/dev/devenv/python2/virtualenvs/temp/bin/get_env_details\n(temp)agravier virtualenvs  $", "group_id": 1535, "id": 283601}, {"user_id": 19191, "stars": [], "topic_id": 11205, "date_created": 1299465728.9808071, "message": "I tried manually changing some #!/usr/bin/env python to #!/usr/bin/env python2 and similar calls wherever I thought it could cause problem, but it didn't help. I also tried the --no-site-packages option, just in case.\n\nI found some people with a similar issue, all under OS X, but while they could solve their problems by pip-upgrading virtualenv, virtualenvwrapper and pip, this didn't work fr me.\n\nAny help or idea?", "group_id": 1535, "id": 283602}, {"user_id": 19191, "stars": [], "topic_id": 11205, "date_created": 1299465540.897768, "message": "Hello,\n\nI'm new to python, trying to get virtualenv to work. The issue as I understand it is that during mkvirtualenv, easy_install is not copied over to env/bin. I encounter the same issue on Linux (Archlinux) 32 and 64 bit.", "group_id": 1535, "id": 283578}, {"user_id": 1760, "stars": [], "topic_id": 11205, "date_created": 1299504171.581876, "message": "Your best option for support is to open a ticket in the tracker. I really only come by this site every few days. That said, does virtualenv work by itself? The wrapper just calls virtualenv from the shell, so knowing if virtualenv works will tell us if the problem is in the wrapper or in the core tool.", "group_id": 1535, "id": 287429}, {"user_id": 1760, "stars": [], "topic_id": 11205, "date_created": 1299504277.414994, "message": "Oh, and do you have X Code installed? You need the developer tools for OS X to get one of the commands used when creating the virtual environment.", "group_id": 1535, "id": 287447}, {"user_id": 19191, "stars": [], "topic_id": 11205, "date_created": 1299506817.8310111, "message": "Thanks for replying! I am under Archlinux, so XCode will not really help :)", "group_id": 1535, "id": 287656}, {"user_id": 19191, "stars": [], "topic_id": 11205, "date_created": 1299507062.1284981, "message": "So, I'll try to find support on their group or tracker virtualenv has one, or contact Ian Bicking.", "group_id": 1535, "id": 287695}, {"user_id": 19191, "stars": [], "topic_id": 11205, "date_created": 1299506844.2258711, "message": "But you are right, virtualenv fails in the same way.", "group_id": 1535, "id": 287660}, {"user_id": 1760, "stars": [], "topic_id": 11205, "date_created": 1299520882.0582139, "message": "@agravier Sorry, I saw your comment about finding other people with the same problem on OS X and thought that meant you were there, too.", "group_id": 1535, "id": 289229}, {"user_id": 8391, "stars": [], "topic_id": 11205, "date_created": 1299525567.1123509, "message": "Haha, all us OSX peeps forget there's another world.", "group_id": 1535, "id": 289869}, {"user_id": 19191, "stars": [], "topic_id": 11205, "date_created": 1299648336.141129, "message": "No problem, Doug. Thanks for pointing me in the right direction. For the record, I started a thread at http://groups.google.com/group/python-virtualenv/browse_thread/thread/74a6585ae31c23b6\nCheers", "group_id": 1535, "id": 302176}]