[{"user_id": 4595, "stars": [], "topic_id": 47207, "date_created": 1319909220.8163359, "message": "I've had inconsistent results with cron jobs over the past 3-4 days; typically when the job does not finish the error message looks something like this:", "group_id": 2873, "id": 2462160}, {"user_id": 4595, "stars": [], "topic_id": 47207, "date_created": 1319909229.507838, "message": "[cron] Running script u'manage.py update senate' for app 26287 (time is now 0 17 2\n[cron] Lost connection to runner; cron job ", "group_id": 2873, "id": 2462161}, {"user_id": 4595, "stars": [], "topic_id": 47207, "date_created": 1319909247.2083099, "message": "previously it had been working fairly well, but i've seen repeated errors during the past few days.", "group_id": 2873, "id": 2462163}, {"user_id": 8740, "stars": [], "topic_id": 47207, "date_created": 1319927222.104943, "message": "Yes, we've been having some intermittent load problems on our runners, which sometimes causes a connection to drop. The task itself is finishing fine, the log messages just aren't getting back - we're looking into it.", "group_id": 2873, "id": 2463786}, {"user_id": 4595, "stars": [], "topic_id": 47207, "date_created": 1319975941.9472871, "message": "ok, thanks. In some cases, though, I've noticed that the task isn't finishing too.", "group_id": 2873, "id": 2467781}]