[{"user_id": 29686, "stars": [], "topic_id": 38348, "date_created": 1307388853.969882, "message": "2011-06-05 19:46:24 [25506] [INFO] Booting worker with pid: 25506\n2011-06-05 19:54:31 [25781] [INFO] Booting worker with pid: 25781\n2011-06-05 21:28:53 [29931] [INFO] Booting worker with pid: 29931\n2011-06-05 23:36:30 [29931] [ERROR] Error handling request\nTraceback (most recent call last):\n  File \"/mnt/bundles/app-19190-6O1Vpf/pyenv/lib/python2.6/site-packages/gunicorn/workers/async.py\", line 67, in handle_request\n    resp.write(item)\n  File \"/mnt/bundles/app-19190-6O1Vpf/pyenv/lib/python2.6/site-packages/gunicorn/http/wsgi.py\", line 256, in write\n    util.write(self.sock, arg, self.chunked)\n  File \"/mnt/bundles/app-19190-6O1Vpf/pyenv/lib/python2.6/site-packages/gunicorn/util.py\", line 178, in write\n    sock.sendall(data)\n  File \"/usr/lib/pymodules/python2.6/eventlet/greenio.py\", line 273, in sendall\n    tail = self.send(data, flags)\n  File \"/usr/lib/pymodules/python2.6/eventlet/greenio.py\", line 259, in send\n    total_sent += fd.send(data[total_sent:], flags)\nerror: [Errno 32] Broken pipe\n2011-06-05 23:36:31 [29931] [WARNING] Failed to send error message.\n2011-06-06 05:51:06 [17711] [INFO] Starting gunicorn 0.12.2\n2011-06-06 05:51:06 [17711] [INFO] Listening at: http://0.0.0.0:18036 (17711)\n2", "group_id": 2873, "id": 1309970}, {"user_id": 29686, "stars": [], "topic_id": 38348, "date_created": 1307388899.1543181, "message": "let me know if you need more info...", "group_id": 2873, "id": 1309986}, {"user_id": 29686, "stars": [], "topic_id": 38348, "date_created": 1307388850.5422721, "message": "getting the following weird error in one of my projects. don't think there is anything i can do about but you might want to know so here goes:", "group_id": 2873, "id": 1309967}, {"user_id": 8740, "stars": [], "topic_id": 38348, "date_created": 1307394641.7368419, "message": "Looks like a filehandle got mis-allocated by our PTY module- we've seen it happen under high load.", "group_id": 2873, "id": 1311637}, {"user_id": 8740, "stars": [], "topic_id": 38348, "date_created": 1307394747.3961771, "message": "The new backend - which is close to release - separates the PTYs into subprocesses for this reason.", "group_id": 2873, "id": 1311671}, {"user_id": 1081, "stars": [], "topic_id": 38348, "date_created": 1307400062.7645659, "message": "@andrewgodwin I've seen these a couple of times as well", "group_id": 2873, "id": 1313523}, {"user_id": 8740, "stars": [], "topic_id": 38348, "date_created": 1307428012.7174981, "message": "Yeah, we've seen the opposite end a few times as well (output printing to stdout) - as I said, we've fixed this by separating things by process in the new back end.", "group_id": 2873, "id": 1317486}]