[{"user_id": 2435, "stars": [], "topic_id": 20451, "date_created": 1303257673.1468849, "message": "If you use py.test to run your tests and Vim to edit code you might be interested in the latest release for pytest.vim a \nVim plugin that lets you run your tests from Vim in a very interactive way.", "group_id": 292, "id": 748954}, {"user_id": 2435, "stars": [], "topic_id": 20451, "date_created": 1303257722.949049, "message": "project docs are in Github: https://github.com/alfredodeza/pytest.vim", "group_id": 292, "id": 748961}, {"user_id": 2435, "stars": [{"date_created": 1303257832.3841431, "user_id": 719}, {"date_created": 1303340607.9258251, "user_id": 8490}, {"date_created": 1303584262.986769, "user_id": 1284}], "topic_id": 20451, "date_created": 1303257745.4366961, "message": "latest release can be downloaded from vim.org: http://www.vim.org/scripts/script.php?script_id=3424", "group_id": 292, "id": 748966}, {"user_id": 2435, "stars": [], "topic_id": 20451, "date_created": 1303257698.19473, "message": "The newly added functionality in this release is PDB capabilities. You can now chose to run a method, class or file tests with `--pdb` or `-s` (standard PDB and capturing py.test flags) to drop to a PDB session.", "group_id": 292, "id": 748957}, {"user_id": 2588, "stars": [], "topic_id": 20451, "date_created": 1303576253.931457, "message": "@alfredodeza This is nice, thanks. Anyone have advice on getting this to work in a Django environment?", "group_id": 292, "id": 789833}, {"user_id": 2435, "stars": [], "topic_id": 20451, "date_created": 1303643742.8788979, "message": "@unbracketed I was not aware that this was a problem. I have tried it with other different frameworks and it works fine. Can you try and run py.test from Vim with ==> :!py.test and ping me the results? Also, it would be neat to follow up on the project's issue list https://github.com/alfredodeza/pytest.vim/issues", "group_id": 292, "id": 794020}, {"user_id": 2588, "stars": [], "topic_id": 20451, "date_created": 1303670298.0829389, "message": "@alfredodeza The problem I was having was that py.test won't collect test files for Django since Django names its test files \"tests.py\".", "group_id": 292, "id": 796062}, {"user_id": 2588, "stars": [], "topic_id": 20451, "date_created": 1303670389.72261, "message": "I tried https://github.com/bfirsh/pytest_django briefly in hopes it would allow pytest to resolve the Django test files but no luck.", "group_id": 292, "id": 796069}, {"user_id": 2435, "stars": [], "topic_id": 20451, "date_created": 1303693366.6348579, "message": "@unbracketed If you are able to run py.test on the command line then you should be able to use pytest.vim Otherwise... you have issues with your setup. If you find that pytest.vim is behaving differently, I would love to take this to the issue list for the project. pytest.vim will not *fix* things that py.test fails to accomplish", "group_id": 292, "id": 797690}, {"user_id": 2588, "stars": [], "topic_id": 20451, "date_created": 1303748614.793242, "message": "@alfredodeza  It's not an issue of whether I can use py.test at all - I can. The issue is that if you run py.test at the root of a Django project it won't collect any tests (assuming you're following the Django convention of naming test file tests.py) This can be remedied by adding a line to pytest.ini to match tests.py files, but this does nothing to resolve the fact that the Django test runner has to be invoked so that the test environment will be setup properly.", "group_id": 292, "id": 804836}, {"user_id": 2588, "stars": [], "topic_id": 20451, "date_created": 1303749032.0573461, "message": "There is a py.test Django test runner available, but that only helps if you're running Django tests in the standard way (manage.py test). http://pypi.python.org/pypi/django-pytest/0.1.3", "group_id": 292, "id": 804876}, {"user_id": 2588, "stars": [], "topic_id": 20451, "date_created": 1303749181.630394, "message": "Anyway, not a high priority. I'll mess around with the other plugin (https://github.com/bfirsh/pytest_django) some rainy day since it seems like the correct approach as far as getting pytest.vim to work.", "group_id": 292, "id": 804887}]