[{"user_id": 281, "stars": [{"date_created": 1299081672.7489209, "user_id": 214}, {"date_created": 1299081791.4387541, "user_id": 3580}], "topic_id": 10133, "date_created": 1299081557.3285961, "message": "it might have to do with how your import paths are setup, when you are outside of your project root, your modules might not be along your python path anytmore", "group_id": 81, "id": 248146}, {"user_id": 3580, "stars": [], "topic_id": 10133, "date_created": 1299081043.542608, "message": "commands provided by other apps work fine.. but for mine I have to cd into myproject and run python manage.py custom_command from there.", "group_id": 81, "id": 248056}, {"user_id": 3580, "stars": [], "topic_id": 10133, "date_created": 1299081784.543925, "message": "That makes sense.. do commands like runserver do some monkeying with the sys path to get around the issue? I guess that's what confuses me, is why built-in commands, and commands from reusable apps (South's migrate, for instance) work fine.", "group_id": 81, "id": 248189}, {"user_id": 3580, "stars": [], "topic_id": 10133, "date_created": 1299081014.307586, "message": "I've been dealing with this for a while and figured I'd ask.. My custom management commands aren't discovered if I run them from outside project root.. ie: python myproject/manage.py custom_command. Thoughts as to why?", "group_id": 81, "id": 248044}, {"user_id": 3580, "stars": [], "topic_id": 10133, "date_created": 1299082097.232439, "message": "err. of course. that makes perfect sense. I'm no longer confused, thanks :)", "group_id": 81, "id": 248247}, {"user_id": 281, "stars": [{"date_created": 1299082319.516175, "user_id": 214}], "topic_id": 10133, "date_created": 1299082064.190681, "message": "generally not, the difference is usually that those packages are installed to your site packages directory via easy_install or pip while your code isn't", "group_id": 81, "id": 248241}]