[{"user_id": 19, "stars": [], "topic_id": 36983, "date_created": 1306463299.8421011, "message": "Ah, that is odd.", "group_id": 591, "id": 1199160}, {"user_id": 19, "stars": [], "topic_id": 36983, "date_created": 1306463192.5169139, "message": "It most definitely is", "group_id": 591, "id": 1199133}, {"user_id": 16762, "stars": [], "topic_id": 36983, "date_created": 1306463185.2580831, "message": "It's not part of that repository", "group_id": 591, "id": 1199132}, {"user_id": 16762, "stars": [], "topic_id": 36983, "date_created": 1306463266.332154, "message": "e.g. https://github.com/SmileyChris/django/commit/e482dfd00b9294b5cd8b5de0a137e58e20a226fe", "group_id": 591, "id": 1199152}, {"user_id": 16762, "stars": [], "topic_id": 36983, "date_created": 1306463280.1407461, "message": "https://github.com/django/django/commit/e482dfd00b9294b5cd8b5de0a137e58e20a226fe", "group_id": 591, "id": 1199156}, {"user_id": 16762, "stars": [], "topic_id": 36983, "date_created": 1306462656.9640861, "message": "e.g., I'm looking at https://github.com/django/django/blame/master/django/contrib/admin/views/main.py#LID100 (that commit isn't part of a django/django branch, which is what I was looking for)", "group_id": 591, "id": 1199050}, {"user_id": 16762, "stars": [], "topic_id": 36983, "date_created": 1306462591.727005, "message": "Unless I'm mistaken, blame seems to cross fork boundries. Is there a way to limit github's blame to a single fork?", "group_id": 591, "id": 1199039}, {"user_id": 19, "stars": [], "topic_id": 36983, "date_created": 1306462779.9185629, "message": "Sure looks to be a part of the django/django repository https://github.com/django/django/commit/df6a0f903155554c0fe27fcb9dd040dbb64bdd87", "group_id": 591, "id": 1199060}, {"user_id": 7080, "stars": [], "topic_id": 36983, "date_created": 1306462922.5363679, "message": "That wouldn't make sense.  How could the line get there if it wasn't in your branch?", "group_id": 591, "id": 1199084}, {"user_id": 16762, "stars": [], "topic_id": 36983, "date_created": 1306463226.952857, "message": "It seems that you can pick the sha from any other repository", "group_id": 591, "id": 1199141}, {"user_id": 16762, "stars": [], "topic_id": 36983, "date_created": 1306463275.0923979, "message": "now let's replace SmileyChris with django", "group_id": 591, "id": 1199155}, {"user_id": 16762, "stars": [], "topic_id": 36983, "date_created": 1306463423.5963321, "message": "I'm guessing all the forks are really just \"one repository\", but I'm not an expert on git or have any idea how github makes it neat network graphs, so that's a total noob guess.", "group_id": 591, "id": 1199177}, {"user_id": 7080, "stars": [], "topic_id": 36983, "date_created": 1306465329.8435071, "message": "why would you blame on a sha that doesn't exist in the repo?", "group_id": 591, "id": 1199415}, {"user_id": 7080, "stars": [], "topic_id": 36983, "date_created": 1306465343.0032201, "message": "you are probably right though.  could be some caching thing", "group_id": 591, "id": 1199418}, {"user_id": 16762, "stars": [], "topic_id": 36983, "date_created": 1306466206.7758501, "message": "I'm not blaming on a sha (not sure that even makes sense)", "group_id": 591, "id": 1199605}, {"user_id": 16762, "stars": [], "topic_id": 36983, "date_created": 1306466223.29826, "message": "i'm blaming against a file in the repository - it's showing me a sha that shouldn't be in that repo", "group_id": 591, "id": 1199608}, {"user_id": 122, "stars": [], "topic_id": 36983, "date_created": 1306473774.27179, "message": "it's a super expensive operation", "group_id": 591, "id": 1200923}, {"user_id": 122, "stars": [], "topic_id": 36983, "date_created": 1306473760.6865129, "message": "As for commits being viewable from any repository, that's a side-effect of git alternates. Essentially all public repositories in a network share a storage area and commit lookup by SHA1 does not verify that the commit is reachable from one of the repositories refs.", "group_id": 591, "id": 1200921}, {"user_id": 122, "stars": [], "topic_id": 36983, "date_created": 1306473653.398109, "message": "Blame view should be fixed now. The blame cache key wasn't specific enough.", "group_id": 591, "id": 1200908}, {"user_id": 16762, "stars": [], "topic_id": 36983, "date_created": 1306487634.555176, "message": "yeah, i'm not that concerned about the cross-repo commit visibility, but it was just added to the confusion of what blame was doing. Thanks again.", "group_id": 591, "id": 1202895}, {"user_id": 16762, "stars": [], "topic_id": 36983, "date_created": 1306487581.1427801, "message": "great!", "group_id": 591, "id": 1202884}]