[{"user_id": 16551, "stars": [], "topic_id": 9859, "date_created": 1299021761.589844, "message": "This can be caused by SELinux restrictions.", "group_id": 81, "id": 241660}, {"user_id": 16551, "stars": [], "topic_id": 9859, "date_created": 1299021854.5601029, "message": "Specifically, the MemoryError in conjunction with ctypes module. Is a known issue that crops up sometimes with Apache/mod_wsgi. Whether that translates to gunicorn under supervisord is a different matter.", "group_id": 81, "id": 241706}, {"user_id": 7691, "stars": [], "topic_id": 9859, "date_created": 1299021896.9939761, "message": "Thanks @GrahamDumleton. It's gunicorn + nginx under supervisor. The other processes that fail are celerybeat and django-celery.", "group_id": 81, "id": 241723}, {"user_id": 7691, "stars": [], "topic_id": 9859, "date_created": 1299021620.2932279, "message": "Really not sure what's going on. Had it on a development server (Ubuntu) and now it's on its production server (RHEL 5.5). All three processes that supervisor is supposed to control error out with the same memory error. This is the stacktrace: http://dpaste.org/6Hba/", "group_id": 81, "id": 241607}, {"user_id": 7691, "stars": [], "topic_id": 9859, "date_created": 1299022490.1145921, "message": "SELinux is actually disabled on this machine...anyone else?", "group_id": 81, "id": 241882}, {"user_id": 28018, "stars": [], "topic_id": 9859, "date_created": 1307057811.022337, "message": "I've got the same problem on RHEL5 with supervisord starting celery.  Interestingly, it didn't happen in my test environment, which was Centos5.  Also, if I let supervisor run celery as root, the MemoryError in ctypes doesn't happen.  It only happens when I tell it to run celery as my deploy user.  SELinux is disabled.", "group_id": 81, "id": 1272716}, {"user_id": 28018, "stars": [], "topic_id": 9859, "date_created": 1307058212.965338, "message": "Oh, also, when I run the process outside of supervisord, as the deploy user, I don't get the MemoryError.  So I'm thinking it has something to do with the process of dropping privileges to the deploy user.", "group_id": 81, "id": 1272743}, {"user_id": 28018, "stars": [], "topic_id": 9859, "date_created": 1307059505.5585611, "message": "Ok, never mind, I just tried running supervisord as my deploy user instead of as root, so it doesn't need to drop permissions, and I still have the problem.  So it must have something to do with the forking it's doing?  sestatus says selinux is disabled.  Maybe it's actually not disabled or something?", "group_id": 81, "id": 1272870}, {"user_id": 28018, "stars": [], "topic_id": 9859, "date_created": 1307063004.1453559, "message": "OK, a terrible way to fix this is to remove the last line in ctypes.py, which is apparently just there to make windows unit tests pass anyway. (located in /usr/lib64/python2.6/ctypes/__init__.py in my case)", "group_id": 81, "id": 1273219}, {"user_id": 12030, "stars": [], "topic_id": 9859, "date_created": 1307082493.6387479, "message": "@kevin1024 I ended up just writing init scripts to start/stop the processes we needed. We were never able to get Supervisord to work right under RHEL 5.5. I may give your work around a try when I have to work on that project again in the coming weeks.", "group_id": 81, "id": 1275203}, {"user_id": 28018, "stars": [], "topic_id": 9859, "date_created": 1307503653.4048059, "message": "er, I said ctypes.py but what I should have said was ctypes/__init__.py, the same line that the error message mentions.", "group_id": 81, "id": 1332784}]