[{"user_id": 275, "stars": [], "topic_id": 16581, "date_created": 1301603188.1145589, "message": "Reverse for 'my_app_project_change' with arguments '(3L,)' and keyword arguments '{}' not found.", "group_id": 81, "id": 495828}, {"user_id": 275, "stars": [], "topic_id": 16581, "date_created": 1301603214.430444, "message": "this is from either the edit screen -> delete, or the list view -> delete", "group_id": 81, "id": 495841}, {"user_id": 275, "stars": [], "topic_id": 16581, "date_created": 1301603222.9622641, "message": "it's working on my dev environment", "group_id": 81, "id": 495845}, {"user_id": 275, "stars": [], "topic_id": 16581, "date_created": 1301603307.5352371, "message": "i'm trying to determine if the django versions are different on the two environments", "group_id": 81, "id": 495863}, {"user_id": 275, "stars": [], "topic_id": 16581, "date_created": 1301603315.4066, "message": "but i'm not sure what could be causing this", "group_id": 81, "id": 495864}, {"user_id": 24006, "stars": [], "topic_id": 16581, "date_created": 1301776499.6660919, "message": "could you show us full traceback?", "group_id": 81, "id": 510255}, {"user_id": 275, "stars": [], "topic_id": 16581, "date_created": 1301782577.8978879, "message": "turns out it was a django 1.2.5 v 1.3 error", "group_id": 81, "id": 510640}, {"user_id": 275, "stars": [], "topic_id": 16581, "date_created": 1301782591.9887509, "message": "after pinning the app to django 1.2.5 it worked again", "group_id": 81, "id": 510641}]